### ISSUE TITLE
No button for me

### ISSUE THREAD

**Issue by Kumicoo** [controlado/refund-last-purchase#1]
Button to refund is not appearing.

Also, can you make it be the last purchase instead of the last champion?

**Comment by controlado** [comment]
Can you show how your plugins folder looks?

Yes, it is possible to refund anything... But I don't know if I would put it because I feel that it deviates a little from the plugin's proposal

**Comment by Kumicoo** [comment]
Sure thing! here is my plugins folder
![image](https://github.com/controlado/refund-last-purchase/assets/35538818/7a29134c-60f1-48fe-b7f1-c570892b2663)


Hm. Is it hard to make like a button you can click to show a list of your purchases with a refund button?

Like, I buy 2 champs. I go to select. There is a button "Show Purchases" or "Refund" and it opens a little window with my last, idk, 5 purchases and a refund button next to them.

Anyways, youre right. it deviates from this plugin's purpose.

But yeah, the refund button doesnt show for me. All other plugins work.

**Comment by Kumicoo** [comment]
![image](https://github.com/controlado/refund-last-purchase/assets/35538818/0d5d1369-c715-43ae-9f17-5b0a5acbe7a1)

**Comment by controlado** [comment]
I found out where the error was coming from, the problem was in [@teisseire117's _utils.js](https://github.com/teisseire117/league-loader-plugins/blob/main/plugins/_utils.js) which only worked correctly if you were using his [auto_accept_button](https://github.com/teisseire117/league-loader-plugins/tree/main/plugins/auto_accept_button), it was hard to reproduce the error...

But I just made an update to [refund-last-purchase](https://github.com/controlado/refund-last-purchase) that solves this problem, update the plugin and follow the installation instructions in the documentation!
